/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soldoutV1;

import javax.swing.JOptionPane;

/**
 *
 * @author cristian
 */
public class guiLogin extends javax.swing.JFrame {

    /**
     * Creates new form guiLogin
     */
    public guiLogin() {
        initComponents();
    }

    public void validateUser() {
        
        
        
        String user = txfUser.getText();
        String password = txfPassword.getText();
        
        if (user.equals("Cris07") && password.equals("cat0707")) {
            gui1_SO step1 = new gui1_SO();
            step1.setVisible(true);
            JOptionPane.showMessageDialog(null, "Bienvenido:" + user);
            dispose();
        }else{ 
            JOptionPane.showMessageDialog(null,
                    "Error: Usuario u/o clave incorrectos, intentalo de nuevo."
                    ,"Datos incorrectos",JOptionPane.ERROR_MESSAGE);
            //JOptionPane.showInternalMessageDialog(null, "Error", "Datos incorrectos", );
            //JOptionPane.showMessageDialog(null, "ERROR", "Datos incorrectos", 0, icon);
            //JOptionPane.showMessageDialog(null, "Error: Usuario u/o Clave incorrectas, intentelo de nuevo");
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfUser = new javax.swing.JTextField();
        txfPassword = new javax.swing.JPasswordField();
        btnLogin = new rsbuttom.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(500, 672));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txfUser.setBackground(new java.awt.Color(255, 255, 255));
        txfUser.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        txfUser.setForeground(new java.awt.Color(0, 0, 0));
        txfUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfUser.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));
        txfUser.setName(""); // NOI18N
        txfUser.setSelectionColor(new java.awt.Color(153, 153, 153));
        getContentPane().add(txfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 200, 30));

        txfPassword.setBackground(new java.awt.Color(255, 255, 255));
        txfPassword.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txfPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfPassword.setToolTipText("");
        txfPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.black));
        txfPassword.setSelectionColor(new java.awt.Color(153, 153, 153));
        getContentPane().add(txfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 200, 30));

        btnLogin.setBackground(new java.awt.Color(51, 51, 51));
        btnLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, java.awt.Color.white));
        btnLogin.setText("Login");
        btnLogin.setColorHover(new java.awt.Color(255, 51, 51));
        btnLogin.setColorNormal(new java.awt.Color(51, 51, 51));
        btnLogin.setColorPressed(new java.awt.Color(0, 153, 51));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guiLogin.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        validateUser();
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(guiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(guiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(guiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(guiLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new guiLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField txfPassword;
    private javax.swing.JTextField txfUser;
    // End of variables declaration//GEN-END:variables
}
